{% set name = "liquidprompt" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8fcfd3a192f6f484cd29e0c5bea02564adf0ee524d6dfad52307ca9d54bffd15

build:
  number: 0

requirements:
  build:
    - sed  # [osx]
    - posix  # [win]
  run:
    - posix  # [win]

test:
  commands:
    - grep -q '${CONDA_PREFIX}' $PREFIX/etc/conda/activate.d/liquidprompt.sh  # [not win]
    - grep -q '${CONDA_PREFIX}' %PREFIX%\etc\conda\activate.d\liquidprompt.sh  # [win]

about:
  home: https://github.com/nojhan/liquidprompt
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: A full-featured & carefully designed adaptive prompt for Bash & Zsh

  description: |
    Liquid Prompt gives you a nicely displayed prompt with useful 
    information when you need it. It shows you what you need when you need
    it. You will notice what changes when it changes, saving time and 
    frustration. You can even use it with your favorite shell – Bash or zsh.
  doc_url: https://github.com/nojhan/liquidprompt/blob/master/README.md
  dev_url: https://github.com/nojhan/liquidprompt

extra:
  recipe-maintainers:
    - sodre
