travis:
  secure:
    BINSTAR_TOKEN: G9r1fUy3N7MdtWpFr6S2CfXR9XmnzRjbbezEn1ISDLaiTcwYPGBQj6XwRCnamdqxPaYVi2UANBs1ZE4dDb0JexvvR4r5yS5obbHkf6p909E4RZFb/aAkFpIdsRweNdqdHrRTr0dm97vHVy6+bRTAr6Ymudx5Nyp5ACUIC79hYeaVw6Bv79/1dNrs3ut4KG+9IGIHwTIYP1/IwY3xOZ7UGRmsge0/yv0YZPph0Dor+esGFo2xsjE77x+gA+to49hHozBSACb9ELvdjmlRXCBCgIqD3kClFzoyA2nXjLRmojjSAuCt7urh1mCHNlQzX+3KxEKNKcBmNZkBUul4/5W4BGaT1AqplzT+e6tXsvz7A/9SMq8Y5g7Liss2pja1PWYSm4IcE6PZ45yZ3JShwzLD9dURf9zccQnnTxT8mkG3pnUtyI+CCMjlQBKSDZe5zjs6V86Tde4v6h97g5L/mqQIL9gcahmCEHRrrX3XWgpcYSfu2OI0E0XqMIqZPOW42bMXazsIKzwPDyqHwnFt7SFLYAOLf3VFKrmv45Iyr6Y3gaE9d2GYry6VeyS8BDiLdTcAHe+CAG8zchXGQ/SwhTMQMNzZ6CGus+8p+Wg1+vJ8H2yb2Vb886q6mRazPzZXuYZs59xajgQo+94o/zV9W0uxIoeFUBAwUlMcMCmuC2xOvmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
