travis:
  secure:
    BINSTAR_TOKEN: pQ3ZHatQxiZGpiy2LX2u4EmWRXUDfI9PDRlgvzE7C8e8Y9kTaAeU6YfIe+kD5imZ/GQRe4RFPRx0jVSjJtVYKUGtRzKAmpXJKE5OCDuYDiz/6rLWyPuEqNueGVsLgNC50jd+D2RoCMfGyQP2xgJTSGOSXYR3Ub18ydVJE533KbPQ8Ccw6wIVw5RPmoO2INh7IIhMftXQlv0fkRtBSgv5fzig7mUm+H/toQjD1Ozia1cwxKkAwV6ULxevW9toj+QRoovLeZUJD0Y+Eit0N48tmIlwzAfcpTrEASlorcE9b91Z8jjbYzBIGL/gz4oTZYEh8mwHEuNDaOVtuHA7v/yW4VLfxFDVFx9lzPcQkI+dynNkyas9njxbWs8uW8CLNgIg09SXGsmUxF1wf5xXog83AHHz41lmeHB//3ivfaTNoibgvd9PsKenaGiXT6qVgAWh6Vm4pjcTJzk+B2a3BD2wBRaJ7pNxLcLg6vyxIek6PfbU9agAH0u+gPnW1xx1paJWZeNGf7sMoQQwilK3St+Tf2RLMl0gcqYfnWslJF5ScZO3JHjmUUaiiEHTvB3ppvOKre27AZdq61E/gHPNv/boekPj0/FDj1X7XwnUJlIHDJmoMqaqRCaqN+Ew5wNODTEMsO9lZFzfU0MfdooHS6Hq5YgePJ5W3DKm/7AEKw+AIoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
